name: PR

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  check-code-generation:
    runs-on: ubuntu-latest
    name: 'Check Code Generation: node-16'
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install deps
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test